---
name: Automatic Docs update

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-doc:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo

      - name: Run auto-doc
        uses: tj-actions/auto-doc@v3
        with:
          use_code_blocks: 'true'
          use_major_version: 'true'

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: |
            README.md

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: "main"
          title: "auto-doc: Updated README.md"
          branch: "chore/auto-doc-update-readme"
          commit-message: "auto-doc: Updated README.md"
          body: "auto-doc: Updated README.md"
