---
name: Lint Codebase

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .github/test/**/*|CHANGELOG.md|.github/ISSUE_TEMPLATE.md|.github/PULL_REQUEST_TEMPLATE.md
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD: false
          VALIDATE_CHECKOV: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_DOCKERFILE_HADOLINT: false
