---
name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAJOR: ${{ steps.release.outputs.major }}
          MINOR: ${{ steps.release.outputs.minor }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://$GITHUB_TOKEN@github.com/google-github-actions/release-please-action.git"
          git tag -d "v$MAJOR" || true
          git tag -d "v$MAJOR.$MINOR" || true
          git push origin :"v$MAJOR" || true
          git push origin :"v$MAJOR.$MINOR" || true
          git tag -a "v$MAJOR" -m "Release v$MAJOR"
          git tag -a "v$MAJOR.$MINOR" -m "Release v$MAJOR.$MINOR"
          git push origin "v$MAJOR"
          git push origin "v$MAJOR.$MINOR"
